// This header file was generated by CoprimeDeltas.hs
#pragma once
#ifndef COPRIME_DELTAS__INCLUDED
#define COPRIME_DELTAS__INCLUDED

#include <stdint.h>

#define COPRIME_MAX_INDEX 5
extern uint32_t coprime_first_step[COPRIME_MAX_INDEX+1];
extern uint8_t* coprime_steps[COPRIME_MAX_INDEX+1];

#endif  // COPRIME_DELTAS__INCLUDED

